name: main ci of root

on:
  push:
    branches:
      - release/renewal
      - develop
      - main
    paths-ignore:
      - 'packages/**'
  pull_request:
    branches:
      - release/renewal
      - develop
      - main
      - feature/*
    paths-ignore:
      - 'packages/**'

jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Check the codes
        run: yarn lint
